name: check_in

on:
  schedule:
    - cron: '0 5 * * *' # 每天UTC时间05:00运行（北京时间13:00）
  workflow_dispatch:

jobs:
  自动签到:
    runs-on: ubuntu-latest
    env:
      LEAFLOW_EMAIL: ${{ secrets.LEAFLOW_EMAIL }}
      LEAFLOW_PASSWORD: ${{ secrets.LEAFLOW_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Playwright and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Run check in Script
        run: python app.py
